// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using iMate.API.Data;

#nullable disable

namespace iMate.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240325181233_SeedingCardsAgain")]
    partial class SeedingCardsAgain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("iMate.API.Data.Models.FormQuestions", b =>
                {
                    b.Property<int>("formQuestionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("formQuestionID"));

                    b.Property<string>("Question")
                        .HasColumnType("text");

                    b.Property<bool>("isHappy")
                        .HasColumnType("boolean");

                    b.Property<string[]>("multipleChoice")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("formQuestionID");

                    b.ToTable("FormQuestions");
                });

            modelBuilder.Entity("iMate.API.Data.Models.MoodEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("moodID")
                        .HasColumnType("integer");

                    b.Property<int>("userID")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("moodID");

                    b.ToTable("MoodEntry");
                });

            modelBuilder.Entity("iMate.API.Data.Models.PadRanges", b =>
                {
                    b.Property<int>("moodID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("moodID"));

                    b.Property<string>("mood")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("valueArousal")
                        .HasColumnType("real");

                    b.Property<float>("valueDominance")
                        .HasColumnType("real");

                    b.Property<float>("valuePleasure")
                        .HasColumnType("real");

                    b.HasKey("moodID");

                    b.ToTable("PadRanges");

                    b.HasData(
                        new
                        {
                            moodID = 1,
                            mood = "Excited",
                            valueArousal = 1f,
                            valueDominance = 1f,
                            valuePleasure = 1f
                        },
                        new
                        {
                            moodID = 2,
                            mood = "Happy",
                            valueArousal = 0.5f,
                            valueDominance = 1f,
                            valuePleasure = 1f
                        },
                        new
                        {
                            moodID = 3,
                            mood = "Loved/ Grateful",
                            valueArousal = 0.2f,
                            valueDominance = 0.8f,
                            valuePleasure = 0.9f
                        },
                        new
                        {
                            moodID = 4,
                            mood = "Relaxed",
                            valueArousal = 0.2f,
                            valueDominance = 0.2f,
                            valuePleasure = 0.9f
                        },
                        new
                        {
                            moodID = 5,
                            mood = "Angry",
                            valueArousal = 0.9f,
                            valueDominance = 1f,
                            valuePleasure = 0.1f
                        },
                        new
                        {
                            moodID = 6,
                            mood = "Stressed",
                            valueArousal = 0.9f,
                            valueDominance = 0.7f,
                            valuePleasure = 0.2f
                        },
                        new
                        {
                            moodID = 7,
                            mood = "Anxious",
                            valueArousal = 0.6f,
                            valueDominance = 0.4f,
                            valuePleasure = 0.1f
                        },
                        new
                        {
                            moodID = 8,
                            mood = "Disgust",
                            valueArousal = 0.7f,
                            valueDominance = 0.45f,
                            valuePleasure = 0f
                        },
                        new
                        {
                            moodID = 9,
                            mood = "Sad",
                            valueArousal = 0.1f,
                            valueDominance = 0.1f,
                            valuePleasure = 0.1f
                        },
                        new
                        {
                            moodID = 10,
                            mood = "Bored",
                            valueArousal = 0.1f,
                            valueDominance = 0.3f,
                            valuePleasure = 0.2f
                        },
                        new
                        {
                            moodID = 11,
                            mood = "Sleepy",
                            valueArousal = 0.4f,
                            valueDominance = 0.4f,
                            valuePleasure = 0.4f
                        },
                        new
                        {
                            moodID = 12,
                            mood = "Lonely",
                            valueArousal = 0.3f,
                            valueDominance = 0f,
                            valuePleasure = 0.1f
                        },
                        new
                        {
                            moodID = 13,
                            mood = "Depressed",
                            valueArousal = 0f,
                            valueDominance = 0f,
                            valuePleasure = 0f
                        });
                });

            modelBuilder.Entity("iMate.API.Data.Models.Settings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("motivationalMessages")
                        .HasColumnType("boolean");

                    b.Property<bool>("practiceReminder")
                        .HasColumnType("boolean");

                    b.Property<bool>("reducedMotion")
                        .HasColumnType("boolean");

                    b.Property<string>("reminderTime")
                        .HasColumnType("text");

                    b.Property<bool>("smartScheduling")
                        .HasColumnType("boolean");

                    b.Property<bool>("soundEffects")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("iMate.API.Data.Models.SlidersQuestions", b =>
                {
                    b.Property<int>("silderQuestionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("silderQuestionID"));

                    b.Property<string>("Question")
                        .HasColumnType("text");

                    b.Property<bool>("isHappy")
                        .HasColumnType("boolean");

                    b.Property<string>("sliderOptionOne")
                        .HasColumnType("text");

                    b.Property<string>("sliderOptionTwo")
                        .HasColumnType("text");

                    b.HasKey("silderQuestionID");

                    b.ToTable("SlidersQuestions");
                });

            modelBuilder.Entity("iMate.API.Data.Models.TarotCards", b =>
                {
                    b.Property<int>("cardID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("cardID"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<int>("cardCreditsValue")
                        .HasColumnType("integer");

                    b.Property<int>("moodID")
                        .HasColumnType("integer");

                    b.Property<int>("targetMoodId")
                        .HasColumnType("integer");

                    b.HasKey("cardID");

                    b.HasIndex("moodID");

                    b.HasIndex("targetMoodId");

                    b.ToTable("TarotCards");

                    b.HasData(
                        new
                        {
                            cardID = 174,
                            Content = "Plan a fun outing or adventure.",
                            cardCreditsValue = 10,
                            moodID = 2,
                            targetMoodId = 1
                        },
                        new
                        {
                            cardID = 175,
                            Content = "Listen to upbeat music and dance.",
                            cardCreditsValue = 10,
                            moodID = 2,
                            targetMoodId = 1
                        },
                        new
                        {
                            cardID = 176,
                            Content = "Engage in a thrilling activity like rollerblading or rock climbing.",
                            cardCreditsValue = 10,
                            moodID = 2,
                            targetMoodId = 1
                        },
                        new
                        {
                            cardID = 177,
                            Content = "Share your excitement with friends or loved ones.",
                            cardCreditsValue = 10,
                            moodID = 2,
                            targetMoodId = 1
                        },
                        new
                        {
                            cardID = 178,
                            Content = "Watch an exciting movie or read an engaging book.",
                            cardCreditsValue = 10,
                            moodID = 2,
                            targetMoodId = 1
                        },
                        new
                        {
                            cardID = 179,
                            Content = "Try a new hobby or learn something new.",
                            cardCreditsValue = 10,
                            moodID = 2,
                            targetMoodId = 1
                        },
                        new
                        {
                            cardID = 180,
                            Content = "Exercise or go for a run to release energy.",
                            cardCreditsValue = 10,
                            moodID = 2,
                            targetMoodId = 1
                        },
                        new
                        {
                            cardID = 181,
                            Content = "Attend a live event or concert.",
                            cardCreditsValue = 10,
                            moodID = 2,
                            targetMoodId = 1
                        },
                        new
                        {
                            cardID = 182,
                            Content = "Set goals and make plans for the future.",
                            cardCreditsValue = 10,
                            moodID = 2,
                            targetMoodId = 1
                        },
                        new
                        {
                            cardID = 183,
                            Content = "Express gratitude for the things that bring you excitement.",
                            cardCreditsValue = 10,
                            moodID = 2,
                            targetMoodId = 1
                        },
                        new
                        {
                            cardID = 184,
                            Content = "Enjoy the moment: Embrace the thrill.",
                            cardCreditsValue = 10,
                            moodID = 2,
                            targetMoodId = 1
                        },
                        new
                        {
                            cardID = 185,
                            Content = "Dance it out: Move to the rhythm.",
                            cardCreditsValue = 10,
                            moodID = 2,
                            targetMoodId = 1
                        },
                        new
                        {
                            cardID = 186,
                            Content = "Visualize success: See your dreams realized.",
                            cardCreditsValue = 10,
                            moodID = 2,
                            targetMoodId = 1
                        },
                        new
                        {
                            cardID = 187,
                            Content = "Spend time with loved ones.",
                            cardCreditsValue = 30,
                            moodID = 1,
                            targetMoodId = 1
                        },
                        new
                        {
                            cardID = 188,
                            Content = "Practice gratitude by listing things you're thankful for.",
                            cardCreditsValue = 15,
                            moodID = 1,
                            targetMoodId = 1
                        },
                        new
                        {
                            cardID = 189,
                            Content = "Engage in activities that bring you joy, such as painting or cooking.",
                            cardCreditsValue = 60,
                            moodID = 1,
                            targetMoodId = 1
                        },
                        new
                        {
                            cardID = 190,
                            Content = "Exercise or go for a walk in nature.",
                            cardCreditsValue = 45,
                            moodID = 1,
                            targetMoodId = 1
                        },
                        new
                        {
                            cardID = 191,
                            Content = "Watch a comedy show or funny movie.",
                            cardCreditsValue = 30,
                            moodID = 1,
                            targetMoodId = 1
                        },
                        new
                        {
                            cardID = 192,
                            Content = "Help someone else or perform acts of kindness.",
                            cardCreditsValue = 30,
                            moodID = 1,
                            targetMoodId = 1
                        },
                        new
                        {
                            cardID = 193,
                            Content = "Reflect on past happy memories.",
                            cardCreditsValue = 15,
                            moodID = 1,
                            targetMoodId = 1
                        },
                        new
                        {
                            cardID = 194,
                            Content = "Practice mindfulness or meditation.",
                            cardCreditsValue = 20,
                            moodID = 1,
                            targetMoodId = 1
                        },
                        new
                        {
                            cardID = 195,
                            Content = "Focus on positive affirmations.",
                            cardCreditsValue = 15,
                            moodID = 1,
                            targetMoodId = 1
                        },
                        new
                        {
                            cardID = 196,
                            Content = "Treat yourself to something you enjoy, like a favourite meal or dessert.",
                            cardCreditsValue = 30,
                            moodID = 1,
                            targetMoodId = 1
                        },
                        new
                        {
                            cardID = 197,
                            Content = "Practice deep breathing or meditation for a few minutes.",
                            cardCreditsValue = 10,
                            moodID = 1,
                            targetMoodId = 1
                        },
                        new
                        {
                            cardID = 198,
                            Content = "Listen to uplifting music or a favourite playlist.",
                            cardCreditsValue = 30,
                            moodID = 1,
                            targetMoodId = 1
                        },
                        new
                        {
                            cardID = 199,
                            Content = "Read a book or listen to an audiobook.",
                            cardCreditsValue = 60,
                            moodID = 1,
                            targetMoodId = 1
                        },
                        new
                        {
                            cardID = 200,
                            Content = "Take a warm bath or shower.",
                            cardCreditsValue = 20,
                            moodID = 1,
                            targetMoodId = 1
                        },
                        new
                        {
                            cardID = 201,
                            Content = "Write down their thoughts and feelings in a journal.",
                            cardCreditsValue = 15,
                            moodID = 1,
                            targetMoodId = 1
                        },
                        new
                        {
                            cardID = 202,
                            Content = "Spend time with a pet, if available.",
                            cardCreditsValue = 15,
                            moodID = 1,
                            targetMoodId = 1
                        },
                        new
                        {
                            cardID = 203,
                            Content = "Plan a future trip or activity to look forward to.",
                            cardCreditsValue = 60,
                            moodID = 1,
                            targetMoodId = 1
                        },
                        new
                        {
                            cardID = 204,
                            Content = "Declutter and organize a small area of their living space.",
                            cardCreditsValue = 30,
                            moodID = 1,
                            targetMoodId = 1
                        },
                        new
                        {
                            cardID = 205,
                            Content = "Look at old photos or videos that bring back happy memories.",
                            cardCreditsValue = 20,
                            moodID = 1,
                            targetMoodId = 1
                        },
                        new
                        {
                            cardID = 206,
                            Content = "Try a new recipe or restaurant.",
                            cardCreditsValue = 60,
                            moodID = 1,
                            targetMoodId = 1
                        },
                        new
                        {
                            cardID = 207,
                            Content = "Create a vision board of their goals and dreams.",
                            cardCreditsValue = 30,
                            moodID = 1,
                            targetMoodId = 1
                        },
                        new
                        {
                            cardID = 208,
                            Content = "Spend quality time with loved ones.",
                            cardCreditsValue = 30,
                            moodID = 3,
                            targetMoodId = 3
                        },
                        new
                        {
                            cardID = 209,
                            Content = "Write a letter or message expressing gratitude to someone special.",
                            cardCreditsValue = 30,
                            moodID = 3,
                            targetMoodId = 3
                        },
                        new
                        {
                            cardID = 210,
                            Content = "Reflect on the positive aspects of your life.",
                            cardCreditsValue = 15,
                            moodID = 3,
                            targetMoodId = 3
                        },
                        new
                        {
                            cardID = 211,
                            Content = "Perform random acts of kindness for others.",
                            cardCreditsValue = 15,
                            moodID = 3,
                            targetMoodId = 3
                        },
                        new
                        {
                            cardID = 212,
                            Content = "Volunteer for a cause you care about.",
                            cardCreditsValue = 60,
                            moodID = 3,
                            targetMoodId = 3
                        },
                        new
                        {
                            cardID = 213,
                            Content = "Hug someone you care about.",
                            cardCreditsValue = 10,
                            moodID = 3,
                            targetMoodId = 3
                        },
                        new
                        {
                            cardID = 214,
                            Content = "Practice self-love and self-care activities.",
                            cardCreditsValue = 45,
                            moodID = 3,
                            targetMoodId = 3
                        },
                        new
                        {
                            cardID = 215,
                            Content = "Keep a gratitude journal and write down things you're thankful for.",
                            cardCreditsValue = 15,
                            moodID = 3,
                            targetMoodId = 3
                        },
                        new
                        {
                            cardID = 216,
                            Content = "Share compliments with others.",
                            cardCreditsValue = 10,
                            moodID = 3,
                            targetMoodId = 3
                        },
                        new
                        {
                            cardID = 217,
                            Content = "Count your blessings and focus on what you have rather than what you lack.",
                            cardCreditsValue = 15,
                            moodID = 3,
                            targetMoodId = 3
                        },
                        new
                        {
                            cardID = 218,
                            Content = "Recall happy memories: Bask in nostalgia.",
                            cardCreditsValue = 20,
                            moodID = 3,
                            targetMoodId = 3
                        },
                        new
                        {
                            cardID = 219,
                            Content = "Practice self-love: Treat yourself kindly.",
                            cardCreditsValue = 30,
                            moodID = 3,
                            targetMoodId = 3
                        },
                        new
                        {
                            cardID = 220,
                            Content = "Say 'I love you': Share affection openly.",
                            cardCreditsValue = 10,
                            moodID = 3,
                            targetMoodId = 3
                        },
                        new
                        {
                            cardID = 221,
                            Content = "Reflect on blessings: Gratitude brings peace.",
                            cardCreditsValue = 15,
                            moodID = 3,
                            targetMoodId = 3
                        },
                        new
                        {
                            cardID = 222,
                            Content = "Take a warm bath or shower.",
                            cardCreditsValue = 20,
                            moodID = 4,
                            targetMoodId = 4
                        },
                        new
                        {
                            cardID = 223,
                            Content = "Practice deep breathing exercises on the home page.",
                            cardCreditsValue = 15,
                            moodID = 4,
                            targetMoodId = 4
                        },
                        new
                        {
                            cardID = 224,
                            Content = "Listen to calming music or nature sounds.",
                            cardCreditsValue = 30,
                            moodID = 4,
                            targetMoodId = 4
                        },
                        new
                        {
                            cardID = 225,
                            Content = "Practice yoga or gentle stretching.",
                            cardCreditsValue = 30,
                            moodID = 4,
                            targetMoodId = 4
                        },
                        new
                        {
                            cardID = 226,
                            Content = "Spend time in nature, such as going for a walk in the park.",
                            cardCreditsValue = 45,
                            moodID = 4,
                            targetMoodId = 4
                        },
                        new
                        {
                            cardID = 227,
                            Content = "Engage in a hobby like knitting or gardening.",
                            cardCreditsValue = 60,
                            moodID = 4,
                            targetMoodId = 4
                        },
                        new
                        {
                            cardID = 228,
                            Content = "Read a book or listen to an audiobook.",
                            cardCreditsValue = 60,
                            moodID = 4,
                            targetMoodId = 4
                        },
                        new
                        {
                            cardID = 229,
                            Content = "Practice mindfulness or meditation.",
                            cardCreditsValue = 20,
                            moodID = 4,
                            targetMoodId = 4
                        },
                        new
                        {
                            cardID = 230,
                            Content = "Get a massage or practice self-massage techniques.",
                            cardCreditsValue = 30,
                            moodID = 4,
                            targetMoodId = 4
                        },
                        new
                        {
                            cardID = 231,
                            Content = "Disconnect from screens and technology for a while.",
                            cardCreditsValue = 60,
                            moodID = 4,
                            targetMoodId = 4
                        },
                        new
                        {
                            cardID = 232,
                            Content = "Unwind: Let go of tension.",
                            cardCreditsValue = 15,
                            moodID = 4,
                            targetMoodId = 4
                        },
                        new
                        {
                            cardID = 233,
                            Content = "Find a cosy spot: Nestle in comfort.",
                            cardCreditsValue = 10,
                            moodID = 4,
                            targetMoodId = 4
                        },
                        new
                        {
                            cardID = 234,
                            Content = "Listen to nature: Soothing sounds of tranquillity.",
                            cardCreditsValue = 30,
                            moodID = 4,
                            targetMoodId = 4
                        },
                        new
                        {
                            cardID = 235,
                            Content = "Drink herbal tea: Sip serenity.",
                            cardCreditsValue = 15,
                            moodID = 4,
                            targetMoodId = 4
                        },
                        new
                        {
                            cardID = 236,
                            Content = "Enjoy a bubble bath: Soak away stress.",
                            cardCreditsValue = 30,
                            moodID = 4,
                            targetMoodId = 4
                        },
                        new
                        {
                            cardID = 237,
                            Content = "Meditate: Quiet the mind.",
                            cardCreditsValue = 20,
                            moodID = 4,
                            targetMoodId = 4
                        },
                        new
                        {
                            cardID = 238,
                            Content = "Take deep breaths to calm down.",
                            cardCreditsValue = 15,
                            moodID = 4,
                            targetMoodId = 5
                        },
                        new
                        {
                            cardID = 239,
                            Content = "Remove yourself from the situation temporarily.",
                            cardCreditsValue = 15,
                            moodID = 4,
                            targetMoodId = 5
                        },
                        new
                        {
                            cardID = 240,
                            Content = "Engage in physical activity to release pent-up energy.",
                            cardCreditsValue = 45,
                            moodID = 4,
                            targetMoodId = 5
                        },
                        new
                        {
                            cardID = 241,
                            Content = "Practice mindfulness or meditation to centre yourself.",
                            cardCreditsValue = 20,
                            moodID = 4,
                            targetMoodId = 5
                        },
                        new
                        {
                            cardID = 242,
                            Content = "Write down your feelings in a journal.",
                            cardCreditsValue = 15,
                            moodID = 4,
                            targetMoodId = 5
                        },
                        new
                        {
                            cardID = 243,
                            Content = "Talk to a trusted friend or family member about what's bothering you.",
                            cardCreditsValue = 30,
                            moodID = 4,
                            targetMoodId = 5
                        },
                        new
                        {
                            cardID = 244,
                            Content = "Practice empathy and try to see the situation from another perspective.",
                            cardCreditsValue = 20,
                            moodID = 4,
                            targetMoodId = 5
                        },
                        new
                        {
                            cardID = 245,
                            Content = "Count to ten before responding to avoid saying something you might regret.",
                            cardCreditsValue = 10,
                            moodID = 4,
                            targetMoodId = 5
                        },
                        new
                        {
                            cardID = 246,
                            Content = "Channel your anger into a constructive activity like cleaning or organizing.",
                            cardCreditsValue = 30,
                            moodID = 4,
                            targetMoodId = 5
                        },
                        new
                        {
                            cardID = 247,
                            Content = "Seek professional help if anger becomes a recurring issue.",
                            cardCreditsValue = 60,
                            moodID = 4,
                            targetMoodId = 5
                        },
                        new
                        {
                            cardID = 248,
                            Content = "Find perspective: Consider the bigger picture.",
                            cardCreditsValue = 20,
                            moodID = 4,
                            targetMoodId = 5
                        },
                        new
                        {
                            cardID = 249,
                            Content = "Use humour: Lighten the mood, watch a comedy.",
                            cardCreditsValue = 30,
                            moodID = 4,
                            targetMoodId = 5
                        },
                        new
                        {
                            cardID = 250,
                            Content = "Practice forgiveness: Let go of resentment.",
                            cardCreditsValue = 20,
                            moodID = 4,
                            targetMoodId = 5
                        },
                        new
                        {
                            cardID = 251,
                            Content = "Journal anger: Write to process emotions.",
                            cardCreditsValue = 15,
                            moodID = 4,
                            targetMoodId = 5
                        },
                        new
                        {
                            cardID = 252,
                            Content = "Take breaks throughout the day to relax and recharge.",
                            cardCreditsValue = 15,
                            moodID = 4,
                            targetMoodId = 6
                        },
                        new
                        {
                            cardID = 253,
                            Content = "Prioritize tasks and break them down into smaller, manageable steps.",
                            cardCreditsValue = 15,
                            moodID = 4,
                            targetMoodId = 6
                        },
                        new
                        {
                            cardID = 254,
                            Content = "Practice deep breathing or progressive muscle relaxation.",
                            cardCreditsValue = 15,
                            moodID = 4,
                            targetMoodId = 6
                        },
                        new
                        {
                            cardID = 255,
                            Content = "Delegate responsibilities: Share the load if possible.",
                            cardCreditsValue = 30,
                            moodID = 4,
                            targetMoodId = 6
                        },
                        new
                        {
                            cardID = 256,
                            Content = "Get organized: maybe make a list of tasks to do.",
                            cardCreditsValue = 20,
                            moodID = 4,
                            targetMoodId = 6
                        },
                        new
                        {
                            cardID = 257,
                            Content = "Engage in physical activity like going for a walk or practicing yoga.",
                            cardCreditsValue = 45,
                            moodID = 4,
                            targetMoodId = 6
                        },
                        new
                        {
                            cardID = 258,
                            Content = "Limit caffeine and sugar intake.",
                            cardCreditsValue = 15,
                            moodID = 4,
                            targetMoodId = 6
                        },
                        new
                        {
                            cardID = 259,
                            Content = "Get plenty of sleep and establish a regular sleep schedule.",
                            cardCreditsValue = 60,
                            moodID = 4,
                            targetMoodId = 6
                        },
                        new
                        {
                            cardID = 260,
                            Content = "Practice time management techniques: try time blocking.",
                            cardCreditsValue = 30,
                            moodID = 4,
                            targetMoodId = 6
                        },
                        new
                        {
                            cardID = 261,
                            Content = "Talk it out: Share feelings with a friend.",
                            cardCreditsValue = 30,
                            moodID = 4,
                            targetMoodId = 6
                        },
                        new
                        {
                            cardID = 262,
                            Content = "Write it down: Journal to process emotions.",
                            cardCreditsValue = 15,
                            moodID = 4,
                            targetMoodId = 6
                        },
                        new
                        {
                            cardID = 263,
                            Content = "Set boundaries: Protect your peace.",
                            cardCreditsValue = 20,
                            moodID = 4,
                            targetMoodId = 6
                        },
                        new
                        {
                            cardID = 264,
                            Content = "Challenge negative thoughts and replace them with positive affirmations.",
                            cardCreditsValue = 20,
                            moodID = 3,
                            targetMoodId = 7
                        },
                        new
                        {
                            cardID = 265,
                            Content = "Engage in activities that distract your mind, such as puzzles or games.",
                            cardCreditsValue = 30,
                            moodID = 3,
                            targetMoodId = 7
                        },
                        new
                        {
                            cardID = 266,
                            Content = "Practice mindfulness or meditation to stay present.",
                            cardCreditsValue = 20,
                            moodID = 3,
                            targetMoodId = 7
                        },
                        new
                        {
                            cardID = 267,
                            Content = "Limit exposure to triggers like caffeine or stressful situations.",
                            cardCreditsValue = 15,
                            moodID = 3,
                            targetMoodId = 7
                        },
                        new
                        {
                            cardID = 268,
                            Content = "Talk to someone you trust about your feelings.",
                            cardCreditsValue = 30,
                            moodID = 3,
                            targetMoodId = 7
                        },
                        new
                        {
                            cardID = 269,
                            Content = "Create a calming environment with soothing music, aromatherapy or just your bed.",
                            cardCreditsValue = 30,
                            moodID = 3,
                            targetMoodId = 7
                        },
                        new
                        {
                            cardID = 270,
                            Content = "Focus on what you can control rather than what you can't.",
                            cardCreditsValue = 20,
                            moodID = 3,
                            targetMoodId = 7
                        },
                        new
                        {
                            cardID = 271,
                            Content = "Exercise to reduce anxiety levels.",
                            cardCreditsValue = 45,
                            moodID = 3,
                            targetMoodId = 7
                        },
                        new
                        {
                            cardID = 272,
                            Content = "Write worries: Release them on paper.",
                            cardCreditsValue = 15,
                            moodID = 3,
                            targetMoodId = 7
                        },
                        new
                        {
                            cardID = 273,
                            Content = "Ground yourself: 5-4-3-2-1 list 5 things you can see, 4 you can touch, 3 you can hear, 2 you can smell, and 1 you can taste.",
                            cardCreditsValue = 20,
                            moodID = 3,
                            targetMoodId = 7
                        },
                        new
                        {
                            cardID = 274,
                            Content = "Find calm: Listen to soothing music.",
                            cardCreditsValue = 30,
                            moodID = 3,
                            targetMoodId = 7
                        },
                        new
                        {
                            cardID = 275,
                            Content = "Stretch and relax: Ease tension physically.",
                            cardCreditsValue = 20,
                            moodID = 3,
                            targetMoodId = 7
                        },
                        new
                        {
                            cardID = 276,
                            Content = "Distract yourself: Engage in a hobby.",
                            cardCreditsValue = 60,
                            moodID = 3,
                            targetMoodId = 7
                        },
                        new
                        {
                            cardID = 277,
                            Content = "Use affirmations: Positive self-talk, you are amazing and you are doing so well right now.",
                            cardCreditsValue = 15,
                            moodID = 3,
                            targetMoodId = 7
                        },
                        new
                        {
                            cardID = 278,
                            Content = "Remove yourself from the source of disgust if possible.",
                            cardCreditsValue = 15,
                            moodID = 4,
                            targetMoodId = 8
                        },
                        new
                        {
                            cardID = 279,
                            Content = "Practice deep breathing to calm your physical reactions.",
                            cardCreditsValue = 15,
                            moodID = 4,
                            targetMoodId = 8
                        },
                        new
                        {
                            cardID = 280,
                            Content = "Focus on positive aspects of the situation or find humour in it.",
                            cardCreditsValue = 20,
                            moodID = 4,
                            targetMoodId = 8
                        },
                        new
                        {
                            cardID = 281,
                            Content = "Engage in a pleasurable activity to shift your focus.",
                            cardCreditsValue = 30,
                            moodID = 4,
                            targetMoodId = 8
                        },
                        new
                        {
                            cardID = 282,
                            Content = "Talk to a friend or loved one about how you're feeling.",
                            cardCreditsValue = 30,
                            moodID = 4,
                            targetMoodId = 8
                        },
                        new
                        {
                            cardID = 283,
                            Content = "Practice acceptance and acknowledge that feelings of disgust are temporary.",
                            cardCreditsValue = 20,
                            moodID = 4,
                            targetMoodId = 8
                        },
                        new
                        {
                            cardID = 284,
                            Content = "Engage in self-care activities to nurture yourself.",
                            cardCreditsValue = 45,
                            moodID = 4,
                            targetMoodId = 8
                        },
                        new
                        {
                            cardID = 285,
                            Content = "Challenge irrational thoughts that may be fuelling your disgust.",
                            cardCreditsValue = 20,
                            moodID = 4,
                            targetMoodId = 8
                        },
                        new
                        {
                            cardID = 286,
                            Content = "Seek out positive distractions like watching a funny movie or going for a walk.",
                            cardCreditsValue = 30,
                            moodID = 4,
                            targetMoodId = 8
                        },
                        new
                        {
                            cardID = 287,
                            Content = "Practice gratitude to shift your perspective.",
                            cardCreditsValue = 15,
                            moodID = 4,
                            targetMoodId = 8
                        },
                        new
                        {
                            cardID = 288,
                            Content = "Acknowledge feelings: Validate your emotions - they are valid.",
                            cardCreditsValue = 15,
                            moodID = 4,
                            targetMoodId = 8
                        },
                        new
                        {
                            cardID = 289,
                            Content = "Vent constructively: Express frustrations calmly.",
                            cardCreditsValue = 30,
                            moodID = 4,
                            targetMoodId = 8
                        },
                        new
                        {
                            cardID = 290,
                            Content = "Practice empathy: Understand different perspectives.",
                            cardCreditsValue = 20,
                            moodID = 4,
                            targetMoodId = 8
                        },
                        new
                        {
                            cardID = 291,
                            Content = "Channel disgust: Use it as motivation for change.",
                            cardCreditsValue = 20,
                            moodID = 4,
                            targetMoodId = 8
                        },
                        new
                        {
                            cardID = 292,
                            Content = "Challenge assumptions: Question underlying beliefs.",
                            cardCreditsValue = 20,
                            moodID = 4,
                            targetMoodId = 8
                        },
                        new
                        {
                            cardID = 293,
                            Content = "Reflect on triggers: Identify what causes discomfort.",
                            cardCreditsValue = 20,
                            moodID = 4,
                            targetMoodId = 8
                        },
                        new
                        {
                            cardID = 294,
                            Content = "Reach out to friends or loved ones for support.",
                            cardCreditsValue = 30,
                            moodID = 3,
                            targetMoodId = 9
                        },
                        new
                        {
                            cardID = 295,
                            Content = "Engage in activities that bring you joy or comfort, like listening to music or cooking your favourite meal.",
                            cardCreditsValue = 45,
                            moodID = 3,
                            targetMoodId = 9
                        },
                        new
                        {
                            cardID = 296,
                            Content = "Practice self-compassion and avoid self-criticism.",
                            cardCreditsValue = 20,
                            moodID = 3,
                            targetMoodId = 9
                        },
                        new
                        {
                            cardID = 297,
                            Content = "Spend time with pets, if you have them, as they can provide comfort and companionship.",
                            cardCreditsValue = 30,
                            moodID = 3,
                            targetMoodId = 9
                        },
                        new
                        {
                            cardID = 298,
                            Content = "Get outside and spend time in nature.",
                            cardCreditsValue = 45,
                            moodID = 3,
                            targetMoodId = 9
                        },
                        new
                        {
                            cardID = 299,
                            Content = "Seek professional help if sadness persists or becomes overwhelming.",
                            cardCreditsValue = 60,
                            moodID = 3,
                            targetMoodId = 9
                        },
                        new
                        {
                            cardID = 300,
                            Content = "Practice mindfulness or meditation to help regulate emotions.",
                            cardCreditsValue = 20,
                            moodID = 3,
                            targetMoodId = 9
                        },
                        new
                        {
                            cardID = 301,
                            Content = "Write down your feelings in a journal.",
                            cardCreditsValue = 15,
                            moodID = 3,
                            targetMoodId = 9
                        },
                        new
                        {
                            cardID = 302,
                            Content = "Engage in activities that give you a sense of accomplishment, like completing a small task or hobby.",
                            cardCreditsValue = 30,
                            moodID = 3,
                            targetMoodId = 9
                        },
                        new
                        {
                            cardID = 303,
                            Content = "Connect with others who may be experiencing similar feelings to feel less alone.",
                            cardCreditsValue = 30,
                            moodID = 3,
                            targetMoodId = 9
                        },
                        new
                        {
                            cardID = 304,
                            Content = "Try something new or engage in a hobby you enjoy.",
                            cardCreditsValue = 10,
                            moodID = 4,
                            targetMoodId = 10
                        },
                        new
                        {
                            cardID = 305,
                            Content = "Reach out to friends or family for social interaction.",
                            cardCreditsValue = 30,
                            moodID = 4,
                            targetMoodId = 10
                        },
                        new
                        {
                            cardID = 306,
                            Content = "Plan an outing or activity to break up the monotony.",
                            cardCreditsValue = 45,
                            moodID = 4,
                            targetMoodId = 10
                        },
                        new
                        {
                            cardID = 307,
                            Content = "Watch a movie or TV show you've been wanting to see.",
                            cardCreditsValue = 30,
                            moodID = 4,
                            targetMoodId = 10
                        },
                        new
                        {
                            cardID = 308,
                            Content = "Take a walk or explore a new area of your neighbourhood.",
                            cardCreditsValue = 45,
                            moodID = 4,
                            targetMoodId = 10
                        },
                        new
                        {
                            cardID = 309,
                            Content = "Read a book or listen to an audiobook.",
                            cardCreditsValue = 60,
                            moodID = 4,
                            targetMoodId = 10
                        },
                        new
                        {
                            cardID = 310,
                            Content = "Volunteer for a cause you care about to add purpose to your day.",
                            cardCreditsValue = 60,
                            moodID = 4,
                            targetMoodId = 10
                        },
                        new
                        {
                            cardID = 311,
                            Content = "Learn something new through online courses or tutorials.",
                            cardCreditsValue = 45,
                            moodID = 4,
                            targetMoodId = 10
                        },
                        new
                        {
                            cardID = 312,
                            Content = "Get creative by drawing, painting, or crafting.",
                            cardCreditsValue = 45,
                            moodID = 4,
                            targetMoodId = 10
                        },
                        new
                        {
                            cardID = 313,
                            Content = "Reflect on your goals and make plans to work towards them.",
                            cardCreditsValue = 30,
                            moodID = 4,
                            targetMoodId = 10
                        },
                        new
                        {
                            cardID = 314,
                            Content = "Take a short nap if possible.",
                            cardCreditsValue = 15,
                            moodID = 1,
                            targetMoodId = 11
                        },
                        new
                        {
                            cardID = 315,
                            Content = "Drink a glass of cold water or splash cold water on your face to wake up.",
                            cardCreditsValue = 15,
                            moodID = 1,
                            targetMoodId = 11
                        },
                        new
                        {
                            cardID = 316,
                            Content = "Get up and move around to increase blood flow and alertness.",
                            cardCreditsValue = 30,
                            moodID = 1,
                            targetMoodId = 11
                        },
                        new
                        {
                            cardID = 317,
                            Content = "Open windows or turn on bright lights to increase exposure to light.",
                            cardCreditsValue = 15,
                            moodID = 1,
                            targetMoodId = 11
                        },
                        new
                        {
                            cardID = 318,
                            Content = "Have a small snack with protein to boost energy levels.",
                            cardCreditsValue = 15,
                            moodID = 1,
                            targetMoodId = 11
                        },
                        new
                        {
                            cardID = 319,
                            Content = "Listen to upbeat music or engage in an activity that stimulates your mind.",
                            cardCreditsValue = 30,
                            moodID = 1,
                            targetMoodId = 11
                        },
                        new
                        {
                            cardID = 320,
                            Content = "Practice deep breathing exercises to increase oxygen flow.",
                            cardCreditsValue = 15,
                            moodID = 1,
                            targetMoodId = 11
                        },
                        new
                        {
                            cardID = 321,
                            Content = "Take a brisk walk outside to get fresh air and wake up your body.",
                            cardCreditsValue = 45,
                            moodID = 1,
                            targetMoodId = 11
                        },
                        new
                        {
                            cardID = 322,
                            Content = "Avoid caffeine late in the day to prevent disrupting your sleep schedule.",
                            cardCreditsValue = 15,
                            moodID = 1,
                            targetMoodId = 11
                        },
                        new
                        {
                            cardID = 323,
                            Content = "Splash cold water: Invigorate your senses.",
                            cardCreditsValue = 15,
                            moodID = 1,
                            targetMoodId = 11
                        },
                        new
                        {
                            cardID = 324,
                            Content = "Stretch: Increase blood flow.",
                            cardCreditsValue = 20,
                            moodID = 1,
                            targetMoodId = 11
                        },
                        new
                        {
                            cardID = 325,
                            Content = "Change environment: Move to a different room.",
                            cardCreditsValue = 20,
                            moodID = 1,
                            targetMoodId = 11
                        },
                        new
                        {
                            cardID = 326,
                            Content = "Reach out to friends or family members for a chat or video call.",
                            cardCreditsValue = 30,
                            moodID = 3,
                            targetMoodId = 12
                        },
                        new
                        {
                            cardID = 327,
                            Content = "Join a club or group with similar interests to meet new people.",
                            cardCreditsValue = 45,
                            moodID = 3,
                            targetMoodId = 12
                        },
                        new
                        {
                            cardID = 328,
                            Content = "Volunteer for a cause you care about to connect with others and make a difference.",
                            cardCreditsValue = 60,
                            moodID = 3,
                            targetMoodId = 12
                        },
                        new
                        {
                            cardID = 329,
                            Content = "Engage in activities you enjoy on your own, such as reading, cooking, or watching a movie.",
                            cardCreditsValue = 45,
                            moodID = 3,
                            targetMoodId = 12
                        },
                        new
                        {
                            cardID = 330,
                            Content = "Spend time with pets, as they can provide companionship and comfort.",
                            cardCreditsValue = 30,
                            moodID = 3,
                            targetMoodId = 12
                        },
                        new
                        {
                            cardID = 331,
                            Content = "Connect with old friends or acquaintances through social media or messaging apps.",
                            cardCreditsValue = 30,
                            moodID = 3,
                            targetMoodId = 12
                        },
                        new
                        {
                            cardID = 332,
                            Content = "Attend social events or gatherings in your community to meet new people.",
                            cardCreditsValue = 45,
                            moodID = 3,
                            targetMoodId = 12
                        },
                        new
                        {
                            cardID = 333,
                            Content = "Practice self-care activities to nurture yourself and boost your mood.",
                            cardCreditsValue = 45,
                            moodID = 3,
                            targetMoodId = 12
                        },
                        new
                        {
                            cardID = 334,
                            Content = "Engage in hobbies or activities that bring you fulfilment and joy.",
                            cardCreditsValue = 45,
                            moodID = 3,
                            targetMoodId = 12
                        },
                        new
                        {
                            cardID = 335,
                            Content = "Volunteer your time to help others, which can provide a sense of purpose and connection.",
                            cardCreditsValue = 60,
                            moodID = 3,
                            targetMoodId = 12
                        },
                        new
                        {
                            cardID = 336,
                            Content = "Write in a journal to express your thoughts and feelings, helping you process emotions.",
                            cardCreditsValue = 15,
                            moodID = 3,
                            targetMoodId = 12
                        },
                        new
                        {
                            cardID = 337,
                            Content = "Focus on building a strong relationship with yourself, practicing self-love and self-acceptance.",
                            cardCreditsValue = 20,
                            moodID = 3,
                            targetMoodId = 12
                        },
                        new
                        {
                            cardID = 338,
                            Content = "Reach out: Talk to someone you trust.",
                            cardCreditsValue = 30,
                            moodID = 3,
                            targetMoodId = 13
                        },
                        new
                        {
                            cardID = 339,
                            Content = "Practice self-care: Nurture your well-being (healthy eating, exercise, sleep hygiene).",
                            cardCreditsValue = 45,
                            moodID = 3,
                            targetMoodId = 13
                        },
                        new
                        {
                            cardID = 340,
                            Content = "Create a routine: Establish structure in your day.",
                            cardCreditsValue = 45,
                            moodID = 3,
                            targetMoodId = 13
                        },
                        new
                        {
                            cardID = 341,
                            Content = "Set small goals: Celebrate every achievement, no matter how small.",
                            cardCreditsValue = 30,
                            moodID = 3,
                            targetMoodId = 13
                        },
                        new
                        {
                            cardID = 342,
                            Content = "Stay active: Engage in physical activity, even a short walk can improve mood.",
                            cardCreditsValue = 45,
                            moodID = 3,
                            targetMoodId = 13
                        },
                        new
                        {
                            cardID = 343,
                            Content = "Take a nap (if possible): Aim for 20-30 minutes to avoid sleep inertia.",
                            cardCreditsValue = 60,
                            moodID = 3,
                            targetMoodId = 13
                        },
                        new
                        {
                            cardID = 344,
                            Content = "Limit isolation: Connect with loved ones, even virtually.",
                            cardCreditsValue = 45,
                            moodID = 3,
                            targetMoodId = 13
                        },
                        new
                        {
                            cardID = 345,
                            Content = "Express yourself: Write in a journal, talk to a therapist, or express yourself creatively.",
                            cardCreditsValue = 30,
                            moodID = 3,
                            targetMoodId = 13
                        },
                        new
                        {
                            cardID = 346,
                            Content = "Focus on the present: Mindfulness exercises can help manage overwhelming thoughts.",
                            cardCreditsValue = 20,
                            moodID = 3,
                            targetMoodId = 13
                        });
                });

            modelBuilder.Entity("iMate.API.Data.Models.User", b =>
                {
                    b.Property<int>("userID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("userID"));

                    b.Property<int>("age")
                        .HasColumnType("integer");

                    b.Property<string>("avatarPath")
                        .HasColumnType("text");

                    b.Property<int>("credits")
                        .HasColumnType("integer");

                    b.Property<string>("gender")
                        .HasColumnType("text");

                    b.Property<int>("settingsID")
                        .HasColumnType("integer");

                    b.Property<int>("streak")
                        .HasColumnType("integer");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("userID");

                    b.HasIndex("settingsID")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("iMate.API.Data.Models.MoodEntry", b =>
                {
                    b.HasOne("iMate.API.Data.Models.PadRanges", "mood")
                        .WithMany()
                        .HasForeignKey("moodID");

                    b.Navigation("mood");
                });

            modelBuilder.Entity("iMate.API.Data.Models.TarotCards", b =>
                {
                    b.HasOne("iMate.API.Data.Models.PadRanges", "mood")
                        .WithMany()
                        .HasForeignKey("moodID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("iMate.API.Data.Models.PadRanges", "targetMood")
                        .WithMany()
                        .HasForeignKey("targetMoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("mood");

                    b.Navigation("targetMood");
                });

            modelBuilder.Entity("iMate.API.Data.Models.User", b =>
                {
                    b.HasOne("iMate.API.Data.Models.Settings", "Settings")
                        .WithOne("user")
                        .HasForeignKey("iMate.API.Data.Models.User", "settingsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Settings");
                });

            modelBuilder.Entity("iMate.API.Data.Models.Settings", b =>
                {
                    b.Navigation("user");
                });
#pragma warning restore 612, 618
        }
    }
}
